# See https://aka.ms/customizecontainer to learn how to customize your debug container and how Visual Studio uses this Dockerfile to build your images for faster debugging.

# This stage is used when running from VS in fast mode (Default for Debug configuration)
FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS base
USER $APP_UID
WORKDIR /app
EXPOSE 8080


# This stage is used to build the service project
FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
ARG BUILD_CONFIGURATION=Release
WORKDIR /src
COPY ["services/Doctorand Departmant/DoctorandDepartmant.api/DoctorandDepartmant.api.csproj", "services/Doctorand Departmant/DoctorandDepartmant.api/"]
COPY ["services/Doctorand Departmant/doctor.application/doctor.application.csproj","services/Doctorand Departmant/doctor.application/"]
COPY ["services/Doctorand Departmant/doctor.infrastructure/doctor.infrastructure.csproj","services/Doctorand Departmant/doctor.infrastructure/"]
COPY ["services/Doctorand Departmant/doctor.core/doctor.core.csproj","services/Doctorand Departmant/doctor.core/"]


RUN dotnet restore "./services/Doctorand Departmant/DoctorandDepartmant.api/DoctorandDepartmant.api.csproj"
COPY . .
WORKDIR "/src/services/Doctorand Departmant/DoctorandDepartmant.api"
RUN dotnet build "./DoctorandDepartmant.api.csproj" -c $BUILD_CONFIGURATION -o /app/build

# This stage is used to publish the service project to be copied to the final stage
FROM build AS publish
ARG BUILD_CONFIGURATION=Release
RUN dotnet publish "./DoctorandDepartmant.api.csproj" -c $BUILD_CONFIGURATION -o /app/publish /p:UseAppHost=false

# This stage is used in production or when running from VS in regular mode (Default when not using the Debug configuration)
FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "DoctorandDepartmant.api.dll"]