# See https://aka.ms/customizecontainer to learn how to customize your debug container and how Visual Studio uses this Dockerfile to build your images for faster debugging.

# This stage is used when running from VS in fast mode (Default for Debug configuration)
FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS base
USER $APP_UID
WORKDIR /app
EXPOSE 8080
EXPOSE 8081


# This stage is used to build the service project
FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
ARG BUILD_CONFIGURATION=Release
WORKDIR /src
COPY ["services/Appointmnent/Appointment.api/Appointment.api.csproj", "services/Appointmnent/Appointment.api/"]
COPY ["services/Appointment/Appointment.Application/Appointment.Application.csproj", "services/Appointment/Appointment.Application/"]
COPY ["services/Appointment/Appointment.Core/Appointment.Core.csproj", "services/Appointment/Appointment.Core/"]
COPY ["services/Appointment/Appointment.Infrastructure/Appointment.Infrastructure.csproj", "services/Appointment/Appointment.Infrastructure/"]
RUN dotnet restore "./services/Appointmnent/Appointment.api/Appointment.api.csproj"
COPY . .
WORKDIR "/src/services/Appoinmnent/Appoinment.api"
RUN dotnet build "./Appoinment.api.csproj" -c $BUILD_CONFIGURATION -o /app/build

# This stage is used to publish the service project to be copied to the final stage
FROM build AS publish
ARG BUILD_CONFIGURATION=Release
RUN dotnet publish "./Appoinment.api.csproj" -c $BUILD_CONFIGURATION -o /app/publish /p:UseAppHost=false

# This stage is used in production or when running from VS in regular mode (Default when not using the Debug configuration)
FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "Appoinment.api.dll"]